# Generated by Django 4.2.2 on 2023-07-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_profile_pic_userprofileinfo_profile_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
    ]
